## Data cleaning

In this section, we will take a look at creating, renaming, and dropping columns; type conversion; and sorting &ndash; all of which make our analysis easier. We will be working with the 2019 Yellow Taxi Trip Data provided by NYC Open Data.

### Read the data

In [147]:
import pandas as pd
df = pd.read_csv('2019_Yellow_Taxi_Trip_Data.csv')

##### DIsplaying the column names

In [148]:
df.columns

Index(['vendorid', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'ratecodeid', 'store_and_fwd_flag',
       'pulocationid', 'dolocationid', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge'],
      dtype='object')

In [149]:
df.head()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2,2019-10-23T16:39:42.000,2019-10-23T17:14:10.000,1,7.93,1,N,138,170,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5
1,1,2019-10-23T16:32:08.000,2019-10-23T16:45:26.000,1,2.00,1,N,11,26,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0
2,2,2019-10-23T16:08:44.000,2019-10-23T16:21:11.000,1,1.36,1,N,163,162,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5
3,2,2019-10-23T16:22:44.000,2019-10-23T16:43:26.000,1,1.00,1,N,170,163,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5
4,2,2019-10-23T16:45:11.000,2019-10-23T16:58:49.000,1,1.96,1,N,163,236,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   vendorid               10000 non-null  int64
 1   tpep_pickup_datetime   10000 non-null  object
 2   tpep_dropoff_datetime  10000 non-null  object
 3   passenger_count        10000 non-null  int64
 4   trip_distance          10000 non-null  float64
 5   ratecodeid             10000 non-null  int64
 6   store_and_fwd_flag     10000 non-null  object
 7   pulocationid           10000 non-null  int64
 8   dolocationid           10000 non-null  int64
 9   payment_type           10000 non-null  int64
 10  fare_amount            10000 non-null  float64
 11  extra                  10000 non-null  float64
 12  mta_tax                10000 non-null  float64
 13  tip_amount             10000 non-null  float64
 14  tolls_amount           10000 non-null  float64
 15  improvement_surcharge  10000 non-null  float64
 16  total_amount           10000 non-null  float64
 17  congestion_surcharge   10000 non-null  float64
dtypes: float64(9), int64(6), object(3)
memory usage: 1.4+ MB

### Dropping columns
Let's start by dropping the ID columns and the `store_and_fwd_flag` column, which we won't be using.

The dollar sign $
is used to check if a matching character is the last character in the string. For example, the regular expression (at\.)$ means: a lowercase a, followed by a lowercase t, followed by a . character and the matcher must be at the end of the string.

"(at\.)" => The fat cat. sat. on the mat.

"(at\.)$" => The fat cat. sat. on the mat.

##### Dropping two columns

In [151]:
df[['vendorid', 'store_and_fwd_flag']]

      vendorid store_and_fwd_flag
0            2                  N
1            1                  N
2            2                  N
3            2                  N
4            2                  N
...        ...                ...
9995         1                  N
9996         1                  N
9997         1                  N
9998         1                  N
9999         1                  N

[10000 rows x 2 columns]

In [152]:
new_df= df.drop(['vendorid', 'store_and_fwd_flag'], axis=1)

In [153]:
new_df

,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2019-10-23T16:39:42.000,2019-10-23T17:14:10.000,1,7.93,1,138,170,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5
1,2019-10-23T16:32:08.000,2019-10-23T16:45:26.000,1,2.00,1,11,26,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0
2,2019-10-23T16:08:44.000,2019-10-23T16:21:11.000,1,1.36,1,163,162,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5
3,2019-10-23T16:22:44.000,2019-10-23T16:43:26.000,1,1.00,1,170,163,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5
4,2019-10-23T16:45:11.000,2019-10-23T16:58:49.000,1,1.96,1,163,236,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2019-10-23T17:39:59.000,2019-10-23T17:49:26.000,2,1.30,1,238,239,1,8.0,3.5,0.5,2.46,0.00,0.3,14.76,2.5
9996,2019-10-23T17:53:02.000,2019-10-23T18:00:45.000,1,1.40,1,239,166,2,8.0,3.5,0.5,0.00,0.00,0.3,12.30,2.5
9997,2019-10-23T17:07:16.000,2019-10-23T17:11:35.000,1,0.70,1,166,152,2,5.0,1.0,0.5,0.00,0.00,0.3,6.80,0.0
9998,2019-10-23T17:38:26.000,2019-10-23T17:49:28.000,2,2.50,1,151,42,1,10.0,1.0,0.5,0.00,0.00,0.3,11.80,0.0
9999,2019-10-23T17:22:14.000,2019-10-23T17:52:09.000,1,3.00,1,237,68,1,19.0,3.5,0.5,2.50,0.00,0.3,25.80,2.5

##### Saving the modified dataframe into the same file

In [154]:
new_df.to_csv('/content/2019_Yellow_Taxi_Trip_Data.csv', index=False)

In [155]:
new_df.columns

Index(['tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count',
       'trip_distance', 'ratecodeid', 'pulocationid', 'dolocationid',
       'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount',
       'tolls_amount', 'improvement_surcharge', 'total_amount',
       'congestion_surcharge'],
      dtype='object')

##### Displaying the column names after modification

In [156]:
new_df = pd.read_csv('2019_Yellow_Taxi_Trip_Data.csv')

In [157]:
new_df.columns

Index(['tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count',
       'trip_distance', 'ratecodeid', 'pulocationid', 'dolocationid',
       'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount',
       'tolls_amount', 'improvement_surcharge', 'total_amount',
       'congestion_surcharge'],
      dtype='object')

### Renaming columns

Next, let's rename the datetime columns to 'pickup' and 'dropoff':

##### Renaming column names and saving the modified dataframe into the the same file

In [158]:
n_df=new_df.rename(columns={'tpep_pickup_datetime': 'pickup', 'tpep_dropoff_datetime': 'dropoff'}, inplace=True)

In [159]:
n_df=new_df.to_csv('/content/2019_Yellow_Taxi_Trip_Data.csv', index=False)

In [160]:
n_df = pd.read_csv('2019_Yellow_Taxi_Trip_Data.csv')

In [161]:
n_df.columns

Index(['pickup', 'dropoff', 'passenger_count', 'trip_distance', 'ratecodeid',
       'pulocationid', 'dolocationid', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge'],
      dtype='object')

##### Displaying the column names

### Type conversion

Notice anything off with the data types?

In [162]:
n_df.dtypes

pickup                    object
dropoff                   object
passenger_count            int64
trip_distance            float64
ratecodeid                 int64
pulocationid               int64
dolocationid               int64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

Both `pickup` and `dropoff` should be stored as datetimes. Let's fix this:

In [163]:
n_df['pickup'] = pd.to_datetime(n_df['pickup'], format='%Y-%m-%d')

In [164]:
n_df['dropoff'] = pd.to_datetime(n_df['pickup'], format='%Y-%m-%d')

In [165]:
n_df.dtypes

pickup                   datetime64[ns]
dropoff                  datetime64[ns]
passenger_count                   int64
trip_distance                   float64
ratecodeid                        int64
pulocationid                      int64
dolocationid                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
dtype: object

### Creating new columns

Let's calculate the following for each row:

1. elapsed time of the trip
2. the tip percentage
3. the total taxes, tolls, fees, and surcharges
4. the average speed of the taxi

In [170]:
n_df['elapsed_time_minutes'] = (n_df['dropoff'] - n_df['pickup'])

In [171]:
n_df.head()

,pickup,dropoff,passenger_count,trip_distance,ratecodeid,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,elapsed_time_minutes
0,2019-10-23 16:39:42,2019-10-23 16:39:42,1,7.93,1,138,170,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5,0.0
1,2019-10-23 16:32:08,2019-10-23 16:32:08,1,2.00,1,11,26,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0,0.0
2,2019-10-23 16:08:44,2019-10-23 16:08:44,1,1.36,1,163,162,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5,0.0
3,2019-10-23 16:22:44,2019-10-23 16:22:44,1,1.00,1,170,163,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5,0.0
4,2019-10-23 16:45:11,2019-10-23 16:45:11,1,1.96,1,163,236,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5,0.0

In [172]:
n_df['tip_percentage'] = (n_df['tip_amount'] / n_df['fare_amount']) * 100

In [173]:
n_df['total_taxes_tolls_fees'] = n_df['tolls_amount'] + n_df['total_amount'] - n_df['fare_amount']

In [174]:
n_df['average_speed_mph'] = n_df['trip_distance'] / (n_df['elapsed_time_minutes'] / 60)

In [175]:
n_df.head()

,pickup,dropoff,passenger_count,trip_distance,ratecodeid,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,elapsed_time_minutes,tip_percentage,total_taxes_tolls_fees,average_speed_mph
0,2019-10-23 16:39:42,2019-10-23 16:39:42,1,7.93,1,138,170,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5,0.0,27.050847,24.52,inf
1,2019-10-23 16:32:08,2019-10-23 16:32:08,1,2.00,1,11,26,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0,0.0,0.000000,1.80,inf
2,2019-10-23 16:08:44,2019-10-23 16:08:44,1,1.36,1,163,162,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5,0.0,21.052632,6.30,inf
3,2019-10-23 16:22:44,2019-10-23 16:22:44,1,1.00,1,170,163,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5,0.0,33.230769,8.62,inf
4,2019-10-23 16:45:11,2019-10-23 16:45:11,1,1.96,1,163,236,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5,0.0,4.761905,4.80,inf

In [ ]:
#importing pandas and numpy libraries
import pandas as pd
import numpy as np

# creating and initializing a nested list
values_list = [[15, 2.5, 100], [20, 4.5, 50], [25, 5.2, 80],
               [45, 5.8, 48], [40, 6.3, 70], [41, 6.4, 90],
               [51, 2.3, 111]]

# creating a pandas dataframe
df = pd.DataFrame(values_list, columns=['Field_1', 'Field_2', 'Field_3'],
                  index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])

# Apply function numpy.square() to square
# the values of one row only i.e. row
# with index name 'd'

In [ ]:
# importing pandas and numpylibraries
import pandas as pd
import numpy as np

# creating and initializing a nested list
values_list = [[1.5, 2.5, 10.0], [2.0, 4.5, 5.0], [2.5, 5.2, 8.0],
               [4.5, 5.8, 4.8], [4.0, 6.3, 70], [4.1, 6.4, 9.0],
               [5.1, 2.3, 11.1]]

# creating a pandas dataframe
df = pd.DataFrame(values_list, columns=['Field_1', 'Field_2', 'Field_3'],
                  index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])
# Apply function numpy.square() to square
# the values of 2 rows only i.e. with row
# index name 'b' and 'f' only

### Sorting by values

We can use the `sort_values()` method to sort based on any number of columns:

### [Exercise 2.1](./workbook.ipynb#Exercise-2.1)

##### Read in the meteorite data from the `Meteorite_Landings.csv` file, rename the `mass (g)` column to `mass`, and drop all the latitude and longitude columns. Sort the result by mass in descending order.

##### Load the CSV file into a DataFrame

In [131]:
import pandas as pd
meteorites = pd.read_csv(r'Meteorite_Landings.csv')

In [132]:
meteorites.head()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"

##### Rename the mass (g) column to mass

In [133]:
meteorites.rename(columns={'mass (g)': 'mass'}, inplace=True)

##### Drop latitude and longitude columns

In [134]:
meteorites.drop(['reclat', 'reclong', 'GeoLocation'], axis=1, inplace=True)

In [136]:
meteorites.columns

Index(['name', 'id', 'nametype', 'recclass', 'mass', 'fall', 'year'], dtype='object')

##### Sort the DataFrame by mass in descending order

In [137]:
meteorites.sort_values(['mass'], ascending=False, inplace=True)

##### Storing the modified dataframe into the same file

In [138]:
meteorites.to_csv('/content/Meteorites_Landings.csv', index=False)

##### Displaying the data here (for the reference purpose) from the modified file

In [139]:
meteorites.head()

,name,id,nametype,recclass,mass,fall,year
16392,Hoba,11890,Valid,"Iron, IVB",60000000.0,Found,01/01/1920 12:00:00 AM
5373,Cape York,5262,Valid,"Iron, IIIAB",58200000.0,Found,01/01/1818 12:00:00 AM
5365,Campo del Cielo,5247,Valid,"Iron, IAB-MG",50000000.0,Found,12/22/1575 12:00:00 AM
5370,Canyon Diablo,5257,Valid,"Iron, IAB-MG",30000000.0,Found,01/01/1891 12:00:00 AM
3455,Armanty,2335,Valid,"Iron, IIIE",28000000.0,Found,01/01/1898 12:00:00 AM